spring:
  application:
    name: Eatpic-spring
  jpa:
    show-sql: false
    generate-ddl: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update   # 이거 이제 계속 update 여야 해요!!!!
        format_sql: false
        use_sql_comments: true
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.MySQLDialect
    database: mysql
  profiles:
    include:
      - database
      - swagger
      - jwt
      - s3
  jwt:
    secret: ${JWT_SECRET_KEY}
    access-token-validity: ${JWT_ACCESS_TOKEN_TIME}

---

# Local Profile
spring:
  config:
    activate:
      on-profile: local
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver

---

# Dev Profile
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    url: ${DEV_DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
